### PR TITLE
add useNativeAnimation prop

### PR DESCRIPTION
**Pull request by alex4dev**
Activate useNativeDriver on Animated API for smoother animations

### CODE REVIEW

**Comment by ArauzVega** [comment]
Someone who fixed it did so as follows: 
 node_modules package> react native-easy-toast> index.js 
and add the following configuration:

In show function:

image

In close function:

image

**Review by piyuaryan — APPROVED** [review]
These changes are required for based on  react-native changes.
Please merge this asap.
Thanks

**Comment by piyuaryan** [comment]
@pabloluz  any idea when would you merge this PR?

**Comment by pabloluz** [comment]
@piyuaryan Although I've approved this PR, I'm not a collaborator of this project (I have no write access to the repo).

If you need that fix (and I think so) I'd suggest you make a fork 'cause, as you can see, this PR is open since August last year.

**Comment by piyuaryan** [comment]
Got it. thanks @pabloluz , I've forked the repo.
Cheers.

**Pull request merged**
