### PR TITLE
Migrate deprecated View.propTypes and React.PropTypes

### LINKED ISSUE #11: 新版本react兼容性警告
Warning: View.propTypes has been deprecated and will be removed in a future version of ReactNative. Use ViewPropTypes instead.

### PR DESCRIPTION
**Pull request by alphasp**
Fix #11

### CODE REVIEW

**Comment by kl** [comment]
👍 We need to merge this because as of the latest React PropTypes has been removed so the code will no longer run as it is now.

**Comment by beeglebug** [comment]
Is there any chance of getting this merged?

**Comment by jjzazuet** [comment]
Hi. Another vote here. React 16 has recently been release and it does break this component at runtime. Thanks!

**Comment by ohtangza** [comment]
@crazycodeboy Could you please merge it because it will be a fatal issue if it's not merged.

**Pull request merged**
