### PR TITLE
fix typescript type definition

### LINKED ISSUE #67: Wrong typescript definition
For example, 'position' is not defined as prop.

### PR DESCRIPTION
**Pull request by Darmody**
fix #67

### CODE REVIEW

**Comment by azizhk** [comment]
👍 
Hi @crazycodeboy can we get this merged.

**Comment by daniel-olsen** [comment]
@crazycodeboy Please merge this - it should be an easy fix and will benefit anyone using TS

**Comment by ssscassio** [comment]
@crazycodeboy Can we get this merged?

**Comment by ataravati** [comment]
@crazycodeboy Please merge this.

**Pull request merged**
